# Based on this tutorial: https://www.youtube.com/watch?v=eB0nUzAI7M8
name: Backend Continuous Integration

on: push

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cleanup Test env
        run: npm ci # same as npm i, but also cleans the env
      - name: Backend Test
        run: npm run ci-test